# Generated by Django 2.1 on 2018-08-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180824_1833'),
        ('shop', '0005_auto_20180817_1618'),
    ]

    operations = [
    ]
