# Generated by Django 2.1 on 2018-08-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20180824_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
