# Generated by Django 2.1 on 2018-08-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='highlight1_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='highlight2_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='highlight3_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='highlight4_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='highlight5_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='highlight6_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
