# Generated by Django 2.1 on 2018-08-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180824_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight1_name',
            new_name='highlight1',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight2_name',
            new_name='highlight2',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight3_name',
            new_name='highlight3',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight4_name',
            new_name='highlight4',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight5_name',
            new_name='highlight5',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight6_name',
            new_name='highlight6',
        ),
    ]
