# Generated by Django 2.1 on 2018-08-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180825_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight1',
            new_name='highlight1_name',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight2',
            new_name='highlight2_name',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight3',
            new_name='highlight3_name',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight4',
            new_name='highlight4_name',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight5',
            new_name='highlight5_name',
        ),
        migrations.RenameField(
            model_name='highlights',
            old_name='highlight6',
            new_name='highlight6_name',
        ),
    ]
