# Generated by Django 2.0 on 2018-08-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180825_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
