# Generated by Django 2.0 on 2018-08-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180831_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='products',
            new_name='items',
        ),
    ]
