# Generated by Django 2.0 on 2018-08-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180831_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='items',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Offer'),
        ),
    ]
