# Generated by Django 2.0 on 2018-08-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180831_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='activate',
        ),
    ]
