# Generated by Django 2.0 on 2018-08-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
    ]
