# Generated by Django 2.0 on 2018-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart_Record',
        ),
    ]
