# Generated by Django 2.0 on 2018-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180829_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_record',
            name='quantity',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
