# Generated by Django 2.0 on 2018-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180901_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_record',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart_record',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart_record',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
