"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'shivamtiwarijackie98@gmail.com'
EMAIL_HOST_PASSWORD = 'leoronaldo'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587




import os


STRIPE_PUBLIC_KEY = 'pk_test_AIsYOWLkOM2ofwPE4TjxjCFV'
STRIPE_SECRET_KEY = 'sk_test_jYOsDffMqUwMoHvHZJGWQuvH'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qz+_hg=!$&rr9a@bt8c2i2q-q2-3d6y(*rnek1js-$26s^&*16'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','127.0.0.2','aditya','192.168.43.180','shivam']


# Application definition

INSTALLED_APPS = [
    'shop.apps.ShopConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'phone_field',
    'mathfilters',
    'social_django',
    'address.apps.AddressConfig',
    'appearance.apps.AppearanceConfig',
    'django.contrib.humanize',
    'paypal.standard.ipn',
]



LOGIN_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
    'social_core.backends.google.GoogleOpenId',  # for Google authentication
    'social_core.backends.google.GoogleOAuth2', 
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.instagram.InstagramOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',

    
)




ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]



TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.social_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.header_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.product_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.banner_front_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.banner_other_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.review_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("shop.context_processors.category_processor")


WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : 'shop',
        'USER' : 'root',
        'PASSWORD' : 'govam',
        'HOST' : 'localhost',
        'PORT' : '8080'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'')

CART_SESSION_ID='cart'

LOGIN_URL= 'login'
#LOGOUT_URL= 'logout'
LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_FACEBOOK_KEY = '251882032326040'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'db5e74f5642a8e71859c5f87e0304a0b'


SOCIAL_AUTH_PINTEREST_KEY = '4984682778002995444'  # App ID
SOCIAL_AUTH_PINTEREST_SECRET = '5143bdf8147b93bb14b1f73eeeaabc473103a3b3515796e5479a081768791809'



SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='942046169697-s7r8q11r8ib0tmblfgk2m605a285n508.apps.googleusercontent.com'  #Paste CLient Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '2cNZlbJb1BvnGOUTGi72zwTg' #Paste Secret Key


SOCIAL_AUTH_INSTAGRAM_KEY = '77cdc32c6d394648b8da3b9234e93d76'
SOCIAL_AUTH_INSTAGRAM_SECRET = 'ac4f2e466df849c8aa853d70ea25a6fd'


SOCIAL_AUTH_TWITTER_KEY = 'Ur76uPSe3coZFGlOIPfTh9ITJ'
SOCIAL_AUTH_TWITTER_SECRET = 'X1yde9dotj3nxBQEQIWPLzBBoIg1IgNQTFgcLelrQi72ZwmnoG'


SOCIAL_AUTH_GITHUB_KEY = '367f2c8cde26bd5a0320'
SOCIAL_AUTH_GITHUB_SECRET = '6882ad23da7c0129eb205cb07eafa318cdfeb5f1'

PAID_FEE_AMOUNT = 1
PAID_FEE_PRODUCT_INFO = "Message showing product details."
PAYMENT_URL_TEST = 'https://test.payu.in/_payment'
PAYMENT_URL_LIVE = 'https://secure.payu.in/_payment'
SERVICE_PROVIDER = "payu_paisa"

PAYPAL_RECEIVER_EMAIL='adityanathtiwari25@gmail.com'
TEST_MODE=True
