# Generated by Django 2.0 on 2018-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='font_name',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
