# Generated by Django 2.0 on 2018-08-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0002_auto_20180827_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='font',
            name='font',
        ),
        migrations.DeleteModel(
            name='Font',
        ),
        migrations.DeleteModel(
            name='Font_Name',
        ),
    ]
