# Generated by Django 2.0 on 2018-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20180828_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
