# Generated by Django 2.0 on 2018-08-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('product_id', models.CharField(max_length=5)),
                ('product_name', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
