# Generated by Django 2.0 on 2018-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180830_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, default=False, null=True),
        ),
    ]
