# Generated by Django 2.0 on 2018-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, default=False, null=True),
        ),
    ]
