# Generated by Django 2.0 on 2018-08-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
