# Generated by Django 2.0 on 2018-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
