# Generated by Django 2.0 on 2018-09-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, default=False, null=True),
        ),
    ]
