# Generated by Django 2.0 on 2018-09-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
